title: 我的博客
subtitle: "liqianqi's blogs"
author: liqianqi
language: zh-CN
timezone: Asia/Shanghai

url: https://liqianqi.github.io
root: /

# 目录
source_dir: source
public_dir: public

# 启用 Fluid 主题
theme: fluid
